In [ ]:
import pandas as pd
df = pd.read_csv("GamingStudy_data.csv")

In [ ]:
df.head()

,S. No.,Timestamp,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GADE,...,Birthplace,Residence,Reference,Playstyle,accept,GAD_T,SWL_T,SPIN_T,Residence_ISO3,Birthplace_ISO3
0,1,42052.00437,0,0,0,0,1,0,0,Not difficult at all,...,USA,USA,Reddit,Singleplayer,Accept,1,23,5.0,USA,USA
1,2,42052.00680,1,2,2,2,0,1,0,Somewhat difficult,...,USA,USA,Reddit,Multiplayer - online - with strangers,Accept,8,16,33.0,USA,USA
2,3,42052.03860,0,2,2,0,0,3,1,Not difficult at all,...,Germany,Germany,Reddit,Singleplayer,Accept,8,17,31.0,DEU,DEU
3,4,42052.06804,0,0,0,0,0,0,0,Not difficult at all,...,USA,USA,Reddit,Multiplayer - online - with online acquaintanc...,Accept,0,17,11.0,USA,USA
4,5,42052.08948,2,1,2,2,2,3,2,Very difficult,...,USA,South Korea,Reddit,Multiplayer - online - with strangers,Accept,14,14,13.0,KOR,USA

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13464 entries, 0 to 13463
Data columns (total 55 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   S. No.           13464 non-null  int64
 1   Timestamp        13464 non-null  float64
 2   GAD1             13464 non-null  int64
 3   GAD2             13464 non-null  int64
 4   GAD3             13464 non-null  int64
 5   GAD4             13464 non-null  int64
 6   GAD5             13464 non-null  int64
 7   GAD6             13464 non-null  int64
 8   GAD7             13464 non-null  int64
 9   GADE             12815 non-null  object
 10  SWL1             13464 non-null  int64
 11  SWL2             13464 non-null  int64
 12  SWL3             13464 non-null  int64
 13  SWL4             13464 non-null  int64
 14  SWL5             13464 non-null  int64
 15  Game             13464 non-null  object
 16  Platform         13464 non-null  object
 17  Hours            13434 non-null  float64
 18  earnings         13464 non-null  object
 19  whyplay          13464 non-null  object
 20  League           11612 non-null  object
 21  highestleague    0 non-null      float64
 22  streams          13364 non-null  float64
 23  SPIN1            13340 non-null  float64
 24  SPIN2            13310 non-null  float64
 25  SPIN3            13324 non-null  float64
 26  SPIN4            13305 non-null  float64
 27  SPIN5            13298 non-null  float64
 28  SPIN6            13308 non-null  float64
 29  SPIN7            13326 non-null  float64
 30  SPIN8            13320 non-null  float64
 31  SPIN9            13306 non-null  float64
 32  SPIN10           13304 non-null  float64
 33  SPIN11           13277 non-null  float64
 34  SPIN12           13296 non-null  float64
 35  SPIN13           13277 non-null  float64
 36  SPIN14           13308 non-null  float64
 37  SPIN15           13317 non-null  float64
 38  SPIN16           13317 non-null  float64
 39  SPIN17           13289 non-null  float64
 40  Narcissism       13441 non-null  float64
 41  Gender           13464 non-null  object
 42  Age              13464 non-null  int64
 43  Work             13426 non-null  object
 44  Degree           11887 non-null  object
 45  Birthplace       13464 non-null  object
 46  Residence        13464 non-null  object
 47  Reference        13449 non-null  object
 48  Playstyle        13464 non-null  object
 49  accept           13050 non-null  object
 50  GAD_T            13464 non-null  int64
 51  SWL_T            13464 non-null  int64
 52  SPIN_T           12814 non-null  float64
 53  Residence_ISO3   13354 non-null  object
 54  Birthplace_ISO3  13343 non-null  object
dtypes: float64(23), int64(16), object(16)
memory usage: 5.6+ MB

In [ ]:
df.describe()

,S. No.,Timestamp,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,SWL1,...,SPIN13,SPIN14,SPIN15,SPIN16,SPIN17,Narcissism,Age,GAD_T,SWL_T,SPIN_T
count,13464.000000,13464.000000,13464.000000,13464.000000,13464.000000,13464.000000,13464.000000,13464.000000,13464.000000,13464.000000,...,13277.000000,13308.000000,13317.000000,13317.000000,13289.000000,13441.000000,13464.000000,13464.000000,13464.000000,12814.000000
mean,7096.839201,42054.841222,0.860963,0.673351,0.965761,0.724079,0.488042,0.911022,0.588755,3.720440,...,0.538827,1.252405,1.411054,0.620635,0.935962,2.027677,20.930407,5.211973,19.788844,19.848525
std,4114.478220,0.272948,0.926542,0.915724,0.982776,0.921971,0.837014,0.931168,0.894408,1.736264,...,0.944180,1.207463,1.349874,0.961853,1.180456,1.061842,3.300897,4.713267,7.229243,13.467493
min,1.000000,42052.004370,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.000000,0.000000,5.000000,0.000000
25%,3532.750000,42054.716548,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.000000,2.000000,14.000000,9.000000
50%,7087.500000,42054.800675,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,4.000000,...,0.000000,1.000000,1.000000,0.000000,0.000000,2.000000,20.000000,4.000000,20.000000,17.000000
75%,10654.250000,42054.932112,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,5.000000,...,1.000000,2.000000,2.000000,1.000000,2.000000,3.000000,22.000000,8.000000,26.000000,28.000000
max,14250.000000,42058.363750,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,7.000000,...,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,63.000000,21.000000,35.000000,68.000000

In [ ]:
df.isnull().sum()

S. No.                 0
Timestamp              0
GAD1                   0
GAD2                   0
GAD3                   0
GAD4                   0
GAD5                   0
GAD6                   0
GAD7                   0
GADE                 649
SWL1                   0
SWL2                   0
SWL3                   0
SWL4                   0
SWL5                   0
Game                   0
Platform               0
Hours                 30
earnings               0
whyplay                0
League              1852
highestleague      13464
streams              100
SPIN1                124
SPIN2                154
SPIN3                140
SPIN4                159
SPIN5                166
SPIN6                156
SPIN7                138
SPIN8                144
SPIN9                158
SPIN10               160
SPIN11               187
SPIN12               168
SPIN13               187
SPIN14               156
SPIN15               147
SPIN16               147
SPIN17               175
Narcissism            23
Gender                 0
Age                    0
Work                  38
Degree              1577
Birthplace             0
Residence              0
Reference             15
Playstyle              0
accept               414
GAD_T                  0
SWL_T                  0
SPIN_T               650
Residence_ISO3       110
Birthplace_ISO3      121
dtype: int64